CREATE TABLE DATOS_FORMULARIO(
    ID_FORMUALRIO NUMBER NOT NULL,
    NOMBRE_FORMULARIO VARCHAR(50) NOT NULL,
    KEY_FORMULARIO VARCHAR(50) NOT NULL,
    LABEL_FORMULARIO VARCHAR(50) NOT NULL,
    REQURIDO_FORMULARIO VARCHAR(20) NOT NULL,
    ORDEN_FORMULARIO VARCHAR(30) NOT NULL,
    CONTROL_TYPE VARCHAR(30) NOT NULL,
    TYPE_FORMULARIO VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID_FORMUALRIO)
);

CREATE SEQUENCE SW_S_DATOS_FORM
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999 
MINVALUE 1;

CREATE OR REPLACE TRIGGER Trigger_DATOS_FORM
BEFORE INSERT OR UPDATE ON DATOS_FORMULARIO
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        SELECT SW_S_DATOS_FORM.nextval INTO :NEW.ID_FORMUALRIO FROM DUAL;
    END IF;
END;