//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_MVC_SerieIII.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_FORMULARIO
    {
        public decimal ID_FORMUALRIO { get; set; }
        public string NOMBRE_FORMULARIO { get; set; }
        public string KEY_FORMULARIO { get; set; }
        public string LABEL_FORMULARIO { get; set; }
        public string REQURIDO_FORMULARIO { get; set; }
        public string ORDEN_FORMULARIO { get; set; }
        public string CONTROL_TYPE { get; set; }
        public string TYPE_FORMULARIO { get; set; }
    }
}
